#!/usr/bin/env python3
import sys
import time
import select
from socket import *

def mapper(fname, offset, size):
    #Create dictionary for words
    words = dict()
    #Create an empty string to hold what is read in
    text = ""
    #Open file and seek to the offset
    f = open(fname, "r")
    f.seek(offset)
    #Continue reading file for size characters and store in a string
    for i in range(size):
        text += f.read(1)
    f.close()
    #Split the string by whitespace
    splitText = text.split()
    #Add all words to dictionary and keep track of counts
    for theWord in splitText:
        if(theWord in words.keys()):
            oldCount = words.get(theWord)
            newCount = int(oldCount) + 1
            words[theWord] = newCount
        else:
            words[theWord] = 1
    #Write the dictionary to the file
    newFile = open(fname + "_I_" + myid, "w")
    for k in words.keys():
        newFile.write(str(k))
        newFile.write(" ")
        newFile.write(str(words.get(k)))
        newFile.write("\n")
    newFile.close()
        

myIncomingConnections = []
myOutgoingConnections = []

ip = '127.0.0.1'
port = sys.argv[1]
cliPort = sys.argv[2]
myid = sys.argv[3]
#port = 5002

#Listen for connection from CLI
server = socket(AF_INET, SOCK_STREAM)
server.setsockopt(SOL_SOCKET, SO_REUSEADDR, 1)
server.bind(('', int(port)))
server.listen(5)
conn, addr = server.accept()
myIncomingConnections.append(conn)

#Open up connection with CLI
sock = socket(AF_INET, SOCK_STREAM)
addr = (ip, int(cliPort))
time.sleep(3)
sock.connect(addr)
myOutgoingConnections.append(sock)

#Listen for commads
while(True):
    data = conn.recv(1024).decode()
    if(not data):
        continue
    else:
        print(data)
        dataList = data.split()
        if(dataList[0].find("map") != -1):
            fname = dataList[1]
            offset = int(dataList[2])
            size = int(dataList[3])
            mapper(fname, offset, size)
